export const menu = [
  {
    id: 1,
    title: "Main",
    listItems: [
      {
        id: 1,
        title: "Homepage",
        url: "/",
        icons: "home.svg",
      },
      {
        id: 2,
        title: "Profile",
        url: "/msgbox",
        icons: "profile.svg",
      },
    ],
  },
  {
    id: 2,
    title: "Lists",
    listItems: [
      {
        id: 1,
        title: "Users",
        url: "/users",
        icons: "user.svg",
      },
      {
        id: 2,
        title: "Products",
        url: "/products",
        icons: "product.svg",
      },
      {
        id: 3,
        title: "Orders",
        url: "/msgbox",
        icons: "order.svg",
      },
      {
        id: 4,
        title: "Posts",
        url: "/msgbox",
        icons: "post2.svg",
      },
    ],
  },
  {
    id: 3,
    title: "General",
    listItems: [
      {
        id: 1,
        title: "Elements",
        url: "/msgbox",
        icons: "element.svg",
      },
      {
        id: 2,
        title: "Notes",
        url: "/msgbox",
        icons: "note.svg",
      },
      {
        id: 3,
        title: "Forms",
        url: "/msgbox",
        icons: "form.svg",
      },
      {
        id: 4,
        title: "Calendar",
        url: "/msgbox",
        icons: "calendar.svg",
      },
    ],
  },
  {
    id: 4,
    title: "Maintenance",
    listItems: [
      {
        id: 1,
        title: "Settings",
        url: "/msgbox",
        icons: "setting.svg",
      },
      {
        id: 2,
        title: "Backups",
        url: "/msgbox",
        icons: "backup.svg",
      },
    ],
  },
  {
    id: 5,
    title: "Analytics",
    listItems: [
      {
        id: 1,
        title: "Charts",
        url: "/msgbox",
        icons: "chart.svg",
      },
      {
        id: 2,
        title: "Logs",
        url: "/msgbox",
        icons: "log.svg",
      },
    ],
  },
];

export const topDealUsers = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    username: "Ealasaid Stains",
    email: "estains0@yandex.ru",
    amount: "424",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    username: "Caz McCrystal",
    email: "cmccrystal1@barnesandnoble.com",
    amount: "344",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    username: "Wang Bisley",
    email: "wbisley2@yandex.ru",
    amount: "470",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    username: "Alyse Champken",
    email: "achampken3@independent.co.uk",
    amount: "692",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    username: "Webster Amdohr",
    email: "wamdohr4@technorati.com",
    amount: "956",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    username: "Maggee Krugmann",
    email: "mkrugmann5@google.nl",
    amount: "1128",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    username: "Rowan Bedford",
    email: "rbedford6@pen.io",
    amount: "481",
  },
];

export const chartBoxUser = [
  {
    id: 1,
    color: "#8884d8",
    icon: "/userIcon.svg",
    title: "Total Users",
    dataKey: "users",
    number: "11.238",
    percentage: 45,
    chartData: [
      { name: "Sun", users: 400 },
      { name: "Mon", users: 600 },
      { name: "Tue", users: 500 },
      { name: "Wed", users: 700 },
      { name: "Thu", users: 400 },
      { name: "Fri", users: 500 },
      { name: "Sat", users: 450 },
    ],
  },
  {
    id: 2,
    color: "#8884d8",
    icon: "/userIcon.svg",
    title: "Total Users",
    dataKey: "users",
    number: "11.238",
    percentage: 12,
    chartData: [
      { name: "Sun", users: 400 },
      { name: "Mon", users: 600 },
      { name: "Tue", users: 500 },
      { name: "Wed", users: 700 },
      { name: "Thu", users: 400 },
      { name: "Fri", users: 500 },
      { name: "Sat", users: 450 },
    ],
  },
  {
    color: "#8884d8",
    icon: "/userIcon.svg",
    title: "Total Users",
    dataKey: "users",
    number: "11.238",
    percentage: 3,
    chartData: [
      { name: "Sun", users: 400 },
      { name: "Mon", users: 600 },
      { name: "Tue", users: 500 },
      { name: "Wed", users: 700 },
      { name: "Thu", users: 400 },
      { name: "Fri", users: 500 },
      { name: "Sat", users: 450 },
    ],
  },
  {
    color: "#8884d8",
    icon: "/userIcon.svg",
    title: "Total Ration",
    dataKey: "users",
    number: "11.238",
    percentage: -6,
    chartData: [
      { name: "Sun", users: 400 },
      { name: "Mon", users: 600 },
      { name: "Tue", users: 500 },
      { name: "Wed", users: 700 },
      { name: "Thu", users: 400 },
      { name: "Fri", users: 500 },
      { name: "Sat", users: 450 },
    ],
  },
];
